=== retinue-app/databank/schema/UpgradeCard.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://schema.retinue.app/UpgradeCard.json",
  "title": "UpgradeCard",

  "description": "Defines an upgrade card.",
  "additionalProperties": false,

  "properties": {
    "name": {
      "description": "Name of the upgrade.",
      "type": "string",
      "minLength": 3,
      "maxLength": 40
    },

    "description": {
      "type": "string",
      "minLength": 3,
      "maxLength": 300
    },

    "keywords": {
      "$ref": "./UpgradeKeywords.json"
    },

    "action": {
      "$ref": "./CardAction.json"
    },

    "usage": {
      "enum": ["Detonate", "Discard", "Exhaust"]
    },

    "type": {
      "$ref": "./UpgradeType.json"
    },

    "restrictions": {
      "$ref": "./TargetSet.json"
    },

    "restrictionsNot": {
      "$ref": "./TargetSet.json"
    },

    "points": {
      "type": "number",
      "minimum": 0
    },

    "weapon": {
      "$ref": "./Weapon.json"
    }
  },

  "required": ["name", "type", "points"]
}

=== retinue-app/databank/src/data/core/Galactic-Republic/Upgrades/Personnel/Phase-I-Clone-Captain.json
{
  "name": "Phase I Clone Captain",
  "points": 15,
  "type": "Personnel",

  "restrictions": {
    "units": ["Phase I Clone Troopers"]
  },

  "usage": "Exhaust",

  "description": "When you activate, you cannot remove suppression tokens or be suppressed during this activation.",

  "keywords": {
    "passiveForUnit": {
      "$Add Upgrade": "Training"
    },
    "passiveForUpgrade": {
      "Leader": null
    }
  }
}

=== retinue-app/databank/data/core/Rebel-Alliance/Upgrades/Hardpoint/M-45-Ion-Blaster.json
{
  "name": "M-45 Ion Blaster",
  "points": 38,
  "type": "Hardpoint",

  "restrictions": {
    "units": ["X-34 Landspeeder"]
  },

  "usage": "Exhaust",

  "weapon": {
    "name": "M-45 Ion Blaster",
    "dice": { "black": 1, "white": 4 },
    "range": [1, 4],
    "keywords": {
      "Fixed": ["Front"],
      "Impact": 1,
      "Ion": 1
    }
  }
}

=== retinue-app/databank/data/core/Rebel-Alliance/Upgrades/Heavy-Weapon/Beskad-Duelist.json
{
  "name": "Beskad Duelist",
  "points": 28,
  "type": "Heavy Weapon",

  "restrictions": {
    "units": ["Mandalorian Resistance"]
  },

  "keywords": {
    "passiveForUnit": {
      "Duelist": null
    }
  },

  "weapon": {
    "name": "Beskad Duelist",
    "range": ["Melee"],
    "dice": { "red": 2 }
  }
}

=== retinue-app/databank/src/data/core/Rebel-Alliance/Upgrades/Personnel/Rebel-Trooper-Captain.json
{
  "name": "Rebel Trooper Captain",
  "points": 14,
  "type": "Personnel",

  "restrictions": {
    "units": ["Rebel Troopers"]
  },

  "usage": "Exhaust",

  "description": "When you activate, you cannot remove suppression tokens or be suppressed during this activation.",

  "keywords": {
    "passiveForUnit": {
      "$Add Upgrade": "Training"
    },
    "passiveForUpgrade": {
      "Leader": null
    }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Armament/Idens-DLT-20A-Rifle.json
{
  "name": "Iden's DLT-20A Rifle",
  "points": 15,
  "type": "Armament",

  "restrictions": {
    "units": ["Iden Versio"],
    "isUnique": true
  },

  "weapon": {
    "name": "Iden's DLT-20A Rifle",
    "range": [1, "Infinite"],
    "dice": { "black": 2 },
    "keywords": {
      "High Velocity": null,
      "Pierce": 1
    }
  }
}

=== retinue-app/databank/src/data/core/Galactic-Republic/Upgrades/Pilot/Veteran-Clone-Pilot.json
{
  "name": "Veteran Clone Pilot",
  "points": 7,
  "type": "Pilot",

  "restrictions": {
    "units": ["TX-130 Saber-class Fighter Tank"]
  },

  "description": "While you or a friendly clone trooper unit at range 1 and in line of sight attacks or defends, you and that units can spend each other's aim,dodge and surge tokens. During the End Phase, ready this card."
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Hardpoint/DW-3-Concussion-Grenade-Launcher.json
{
  "name": "DW-3 Concussion Grenade Launcher",
  "points": 15,
  "type": "Hardpoint",

  "restrictions": {
    "units": ["AT-ST"]
  },

  "weapon": {
    "name": "DW-3 Concussion Grenade Launcher",
    "dice": { "black": 2 },
    "range": [1, 2],
    "keywords": {
      "Blast": null,
      "Fixed": ["Front"]
    }
  }
}

=== retinue-app/databank/src/data/core/Galactic-Republic/Upgrades/Heavy-Weapon/DC-15x-ARC-Trooper.json
{
  "name": "DC-15x ARC Trooper",
  "points": 31,
  "type": "Heavy Weapon",

  "restrictions": {
    "units": ["ARC Troopers"]
  },

  "weapon": {
    "name": "DC-15x ARC Trooper",
    "range": [1, 5],
    "dice": { "red": 1, "black": 1 },
    "keywords": {
      "Critical": 1,
      "Immune": ["Deflect"],
      "Lethal": 1
    }
  }
}
