=== retinue-app/databank/schema/UpgradeCard.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://schema.retinue.app/UpgradeCard.json",
  "title": "UpgradeCard",

  "description": "Defines an upgrade card.",
  "additionalProperties": false,

  "properties": {
    "name": {
      "description": "Name of the upgrade.",
      "type": "string",
      "minLength": 3,
      "maxLength": 40
    },

    "description": {
      "type": "string",
      "minLength": 3,
      "maxLength": 300
    },

    "keywords": {
      "$ref": "./UpgradeKeywords.json"
    },

    "action": {
      "$ref": "./CardAction.json"
    },

    "usage": {
      "enum": ["Detonate", "Discard", "Exhaust"]
    },

    "type": {
      "$ref": "./UpgradeType.json"
    },

    "restrictions": {
      "$ref": "./TargetSet.json"
    },

    "restrictionsNot": {
      "$ref": "./TargetSet.json"
    },

    "points": {
      "type": "number",
      "minimum": 0
    },

    "weapon": {
      "$ref": "./Weapon.json"
    }
  },

  "required": ["name", "type", "points"]
}

=== retinue-app/databank/data/core/Neutral/Upgrades/Comms/Integrated-Comms-Antenna.json
{
  "name": "Integrated Comms Antenna",
  "points": 3,
  "type": "Comms",

  "restrictions": {
    "unitTypes": [
      {
        "primary": "Trooper",
        "secondary": "Droid Trooper"
      }
    ]
  },

  "description": "During the Command Phase, you can be issued orders by friendly Commander or Operative inits at range 1-4."
}

=== retinue-app/databank/src/data/core/Separatist-Alliance/Upgrades/Armament/Vibroswords.json
{
  "name": "Vibroswords",
  "points": 6,
  "type": "Armament",

  "restrictions": {
    "units": ["BX-series Droid Commandos"]
  },

  "keywords": {
    "passiveForUnit": {
      "Charge": null
    }
  },

  "weapon": {
    "name": "Vibroswords",
    "range": ["Melee"],
    "dice": { "red": 1, "white": 1 }
  }
}

=== retinue-app/databank/data/core/Neutral/Upgrades/Force/Force-Guidance.json
{
  "name": "Force Guidance",
  "points": 10,
  "type": "Force",

  "usage": "Exhaust",

  "action": {
    "actions": 0,
    "target": {
      "amount": 2,
      "range": [1, 2],
      "is": {
        "hostile": "Friendly"
      }
    },
    "grants": {
      "tokens": {
        "Surge": 1
      }
    }
  }
}

=== retinue-app/databank/src/data/core/Neutral/Upgrades/Gear/Emergency-Stims.json
{
  "name": "Emergency Stims",
  "points": 8,
  "type": "Gear",

  "description": "During an attack, when you would suffer wounds, prevent up to 2 wounds and place an equal number of wound tokens on this card instead. If you do, at the end of your next activation, discard each token on this card and suffer wounds equal to the number of tokens discarded."
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Personnel/Stormtrooper-Specialist.json
{
  "name": "Stormtrooper Specialist",
  "points": 15,
  "type": "Personnel",

  "restrictions": {
    "units": ["Stormtroopers"]
  },

  "usage": "Exhaust",

  "action": {
    "actions": 0,
    "description": "Gain 1 aim token or 1 surge token.",
    "target": {
      "is": "Self"
    },
    "grants": {
      "tokens": {
        "Aim": 1,
        "Surge": 1
      },
      "maxTokensOfAnyType": 1
    }
  },

  "keywords": {
    "passiveForUnit": {
      "$Add Upgrade": "Gear"
    }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Armament/E-11D-Grenade-Launcher-Config.json
{
  "name": "E-11D Grenade Launcher Config",
  "points": 8,
  "type": "Armament",

  "restrictions": {
    "units": ["Imperial Death Troopers"]
  },

  "usage": "Exhaust",

  "keywords": {
    "passiveForUpgrade": {
      "Reconfigure": "E-11D Focus Fire Config"
    }
  },

  "weapon": {
    "name": "E-11D Grenade Launcher Config",
    "range": [1, 2],
    "dice": { "red": 1 },
    "keywords": {
      "Blast": null
    }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Pilot/General-Weiss.json
{
  "name": "General Weiss",
  "points": 10,
  "type": "Pilot",

  "restrictions": {
    "factions": ["Galactic Empire"],
    "unitTypes": [{ "Vehicle": "Ground Vehicle" }],
    "isUnique": true
  },

  "usage": "Exhaust",

  "action": {
    "actions": 0,
    "description": "Until the end of your activation, you gain Arsenal 2.",
    "target": {
      "is": "Self"
    },
    "grants": {
      "keywords": {
        "Arsenal": 2
      },
      "duration": "EndOfActivation"
    }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Armament/Idens-TL-50-Repeater.json
{
  "name": "Iden's TL-50 Repeater",
  "points": 15,
  "type": "Armament",

  "restrictions": {
    "units": ["Iden Versio"],
    "isUnique": true
  },

  "weapon": {
    "name": "Iden's TL-50 Repeater",
    "range": [1, 3],
    "dice": { "red": 2, "black": 1, "white": 2 },
    "keywords": {
      "Critical": 1,
      "Impact": 1
    }
  }
}
