=== retinue-app/databank/schema/UpgradeCard.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://schema.retinue.app/UpgradeCard.json",
  "title": "UpgradeCard",

  "description": "Defines an upgrade card.",
  "additionalProperties": false,

  "properties": {
    "name": {
      "description": "Name of the upgrade.",
      "type": "string",
      "minLength": 3,
      "maxLength": 40
    },

    "description": {
      "type": "string",
      "minLength": 3,
      "maxLength": 300
    },

    "keywords": {
      "$ref": "./UpgradeKeywords.json"
    },

    "action": {
      "$ref": "./CardAction.json"
    },

    "usage": {
      "enum": ["Detonate", "Discard", "Exhaust"]
    },

    "type": {
      "$ref": "./UpgradeType.json"
    },

    "restrictions": {
      "$ref": "./TargetSet.json"
    },

    "restrictionsNot": {
      "$ref": "./TargetSet.json"
    },

    "points": {
      "type": "number",
      "minimum": 0
    },

    "weapon": {
      "$ref": "./Weapon.json"
    }
  },

  "required": ["name", "type", "points"]
}

=== retinue-app/databank/data/core/Separatist-Alliance/Upgrades/Heavy-Weapon/Dioxis-Mine-Saboteur.json
{
  "name": "Dioxis Mine Saboteur",
  "points": 28,
  "type": "Heavy Weapon",

  "restrictions": {
    "units": ["BX-series Droid Commandos"]
  },

  "usage": "Detonate",

  "keywords": {
    "passiveForUnit": {
      "Detonate": {
        "amount": 1,
        "explosive": "Dioxis Mine"
      }
    }
  },

  "weapon": {
    "name": "Dioxis Mine",
    "surge": "Hit",
    "range": [1],
    "dice": {
      "black": 1,
      "white": 2
    },
    "keywords": {
      "Blast": null,
      "Poison": 1
    }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Armament/CR-24-Flame-Rifle.json
{
  "name": "CR-24 Flame Rifle",
  "points": 20,
  "type": "Armament",

  "restrictions": {
    "units": ["Dewback Rider"]
  },

  "weapon": {
    "name": "CR-24 Flame Rifle",
    "range": [1],
    "dice": { "black": 1, "white": 1 },
    "keywords": {
      "Blast": null,
      "Spray": null
    }
  }
}

=== retinue-app/databank/data/core/Rebel-Alliance/Upgrades/Armament/A-300-Short-Range-Config.json
{
  "name": "A-300 Short Range Config",
  "points": 6,
  "type": "Armament",

  "restrictions": {
    "units": ["Rebel Pathfinders"]
  },

  "keywords": {
    "passiveForUpgrade": {
      "Reconfigure": "A-300 Long Range Config"
    }
  },

  "weapon": {
    "name": "A-300 Short Range Config",
    "range": [1, 2],
    "dice": { "red": 1 }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Personnel/Stormtrooper-Captain.json
{
  "name": "Stormtrooper Captain",
  "points": 15,
  "type": "Personnel",

  "restrictions": {
    "units": ["Stormtroopers"]
  },

  "usage": "Exhaust",

  "description": "When you activate, you cannot remove suppression tokens or be suppressed during this activation.",

  "keywords": {
    "passiveForUnit": {
      "$Add Upgrade": "Training"
    },
    "passiveForUpgrade": {
      "Leader": null
    }
  }
}

=== retinue-app/databank/data/core/Galactic-Empire/Upgrades/Hardpoint/AT-ST-Mortar-Launcher.json
{
  "name": "AT-ST Mortar Launcher",
  "points": 10,
  "type": "Hardpoint",

  "restrictions": {
    "units": ["AT-ST"]
  },

  "weapon": {
    "name": "AT-ST Mortar Launcher",
    "dice": { "white": 3 },
    "range": [4, "Infinite"],
    "keywords": {
      "Fixed": ["Front"],
      "Suppressive": null
    }
  }
}

=== retinue-app/databank/data/core/Separatist-Alliance/Upgrades/Armament/DT-57-Annihilator.json
{
  "name": "DT-57 \"Annihilator\"",
  "points": 12,
  "type": "Armament",

  "restrictions": {
    "units": ["General Grievous"],
    "isUnique": true
  },

  "weapon": {
    "name": "DT-57 \"Annihilator\"",
    "range": ["Melee", 1, 2],
    "dice": { "black": 2, "white": 2 },
    "keywords": {
      "Critical": 1,
      "Pierce": 1,
      "Versatile": null
    }
  }
}

=== retinue-app/databank/src/data/core/Rebel-Alliance/Upgrades/Personnel/2-1B-Medical-Droid.json
{
  "name": "2-1B Medical Droid",
  "points": 18,
  "type": "Personnel",

  "restrictions": {
    "factions": ["Rebel Alliance"]
  },

  "keywords": {
    "actions": {
      "Treat": {
        "actions": 0,
        "amount": 1,
        "capacity": 2
      }
    },

    "passiveForUpgrade": {
      "Noncombatant": null
    }
  }
}

=== retinue-app/databank/data/core/Rebel-Alliance/Upgrades/Gear/Electro-Grappling-Line.json
{
  "name": "Electro Grappling Line",
  "points": 5,
  "type": "Gear",

  "restrictions": {
    "units": ["Sabine Wren"]
  },

  "usage": "Exhaust",

  "action": {
    "actions": 1,
    "target": {
      "range": [1],
      "inLineOfSight": true,
      "is": {
        "unitTypes": ["Trooper"],
        "hostile": "Enemy"
      }
    },
    "grants": {
      "tokens": {
        "Immobilize": 2,
        "Suppression": 2
      }
    }
  }
}
